version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/0-project.conf:/etc/nginx/conf.d/0-project.conf
      - ./nginx/z-wordpress.conf:/etc/nginx/z-wordpress.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=https_redirect@file"
      - "traefik.http.routers.${PROJECT_NAME}_nginx_secure.entrypoints=webs"
      - "traefik.http.routers.${PROJECT_NAME}_nginx_secure.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx_secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx_secure.tls.certresolver=acme_certification"

  php:
    image: wodby/wordpress-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mariadb
      - redis
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: 1000
      PHP_FPM_GROUP: 1000
      BASE_URL: $PROJECT_BASE_URL
    volumes:
      - ./wordpress:/var/www/html
      - ./php/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - ./php/GeoLiteCity.dat:/usr/share/GeoIP/GeoIPCity.dat
  redis:
    image: wodby/redis:$REDIS_TAG
    container_name: "${PROJECT_NAME}_redis"


networks:
  default:
